Repository cloudposse/terraform-aws-cloudfront-s3-cdn, pull requests merged in 2021-12, with the labels that each got.

#202 Chore: Update `auto-release` (`release-drafter`) GHA workflow to latest distribution; fix Terratest
  .github/auto-release.yml
  .github/workflows/auto-release.yml
  examples/complete/deployment.tf
  test/src/Makefile
Labels: bug, no-release

#201 Chore: Bump Dependency Module Versions
  .github/CODEOWNERS
  .github/mergify.yml
  .github/workflows/auto-format.yml
  .github/workflows/validate-codeowners.yml
  README.md
  docs/terraform.md
  main.tf
Labels: patch, no-release

#203 Fix: Do Not Hardcode AWS Partition
  README.md
  docs/terraform.md
  examples/complete/deployment.tf
  examples/complete/main.tf
  main.tf
Labels: patch, no-release

#199 Feat: Add `external_aliases` Which Will Not Have CNAMEs Created for Them
  README.md
  docs/terraform.md
  main.tf
  variables.tf
Labels: enhancement, no-release

#204 Feat: `lambda@edge` submodule
  README.md
  README.yaml
  examples/complete/lambda-at-edge.tf
  examples/complete/lambda-at-edge.us-east-2.tfvars
  examples/complete/main.tf
  examples/complete/outputs.tf
  examples/complete/variables.tf
  examples/complete/versions.tf
  modules/lambda@edge/README.md
  modules/lambda@edge/archives/.gitignore
  modules/lambda@edge/context.tf
  modules/lambda@edge/main.tf
  modules/lambda@edge/outputs.tf
  modules/lambda@edge/package.tf
  modules/lambda@edge/variables.tf
  modules/lambda@edge/versions.tf
  test/src/Makefile
  test/src/examples_complete_test.go
Labels: enhancement
