Repository cloudposse/terraform-aws-cloudfront-s3-cdn, pull requests merged in 2022-01, with the labels that each got.

#208 fix: set viewer_certificate.ssl_support_method to a non-empty value
  README.md
  main.tf
Labels: no-release

#209 Feat: Add Support for S3 Object Ownership Controls
  README.md
  docs/terraform.md
  main.tf
  variables.tf
  versions.tf
Labels: no-release

#213 fix: handle viewer_certificate.ssl_support_method with CF default certificate
  main.tf
Labels: bug, patch, no-release

#210 [main.tf] Updated conditions with included cache_policy_id variable
  main.tf
Labels: bug, no-release
