Repository cloudposse/terraform-aws-cloudfront-s3-cdn, pull requests merged in 2024-03, with the labels that each got.

#298 Update Scaffolding
  .github/mergify.yml
  README.md
  README.yaml
Labels: auto-update, no-release, do not merge, migration

#302 Add GitHub Settings
  .github/settings.yml
Labels: auto-update, no-release, migration

#301 BucketOwnerEnforced s3 buckets can't have an acl
  main.tf
Labels: needs-cloudposse

#295 Add support for realtime log config to ordered_cache
  README.md
  docs/terraform.md
  main.tf
  variables.tf
Labels: triage
